### PR TITLE
do the seed file

### LINKED ISSUE #34: Create seed file
### Why

Create a seed in order to fill in product names, brands, prices, description, user first and last names, email addresses and delivery addresses

### To Do

- [ ] Fill in Factory Bot files
- [ ] Fill in seed with right faker fields
- [ ] Remember to add stuff into regression testing document

### Must Have

- [ ] DB is created and migrated

### PR DESCRIPTION
**Pull request by olivdums**
Hello, thanks for review, please pay attention to the last two seeds on the join tables. thanks. Closes #34

### CODE REVIEW

File: db/seeds.rb [hunk 1]
```diff
@@ -7,3 +7,64 @@
...
+    price: Faker::Number.decimal(2),
+    description: Faker::TvShows::GameOfThrones.quote,
+    title: Faker::House.unique.furniture,
+    created_at: Time.zone.today,
+    updated_at: Time.zone.today
+  )
+  p "PRODUCT #{i} : créé"
+
+  User.create!(
+    email: Faker::Number.decimal(2),
```
Comment (GauthierTH) [inline db/seeds.rb]: wrong faker

File: db/seeds.rb [hunk 2]
```diff
@@ -7,3 +7,64 @@
...
+    password: "password",
+    password_confirmation: "password",
+    confirmed_at: Time.zone.today
+  )
+  p "USER #{i} : créé"
+
+  Profile.create!(
```
Comment (GauthierTH) [inline db/seeds.rb]: miss user_id

File: db/seeds.rb [hunk 3]
```diff
@@ -7,3 +7,64 @@
 #
 #   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
 #   Character.create(name: 'Luke', movie: movies.first)
+
+1.upto(10) do |i|
+  Product.create!(
+    price: Faker::Number.decimal(2),
+    description: Faker::TvShows::GameOfThrones.quote,
+    title: Faker::House.unique.furniture,
+    created_at: Time.zone.today,
```
Comment (GauthierTH) [inline db/seeds.rb]: create_at, updated_at necessary ?
